name: "Tests"

on: [push, pull_request]

jobs:
    linux-tests:
        name: "Linux-Tests with PHP ${{ matrix.php-versions }}, experimental: ${{ matrix.experimental }}"
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}

        strategy:
            fail-fast: false
            matrix:
                php-versions: ['8.0', '8.1', '8.2', '8.3', '8.4']
                experimental: [false]
                include:
                  - php-versions: '8.5'
                    experimental: true

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    ini-values: memory_limit=1G

            -   name: If PHP 8.0 is used, adapt composer.json
                run: |
                    chmod +x test/adjust_composer_for_php80.sh
                    ./test/adjust_composer_for_php80.sh

            -   name: Install Composer dependencies
                run: composer update --no-progress --no-suggest --prefer-dist --optimize-autoloader

            -   name: Install other dependencies
                run: sudo apt-get update && sudo apt-get install graphviz raptor2-utils

            -   name: Tests
                run: vendor/bin/phpunit

            -   name: Static Analysis
                run: vendor/bin/phpstan analyse

    windows-tests:
        name: "Windows-Tests with PHP ${{ matrix.php-versions }}, experimental: ${{ matrix.experimental }}"
        runs-on: windows-latest
        continue-on-error: ${{ matrix.experimental }}

        strategy:
            fail-fast: false
            matrix:
                php-versions: ['8.0', '8.1', '8.2', '8.3', '8.4']
                experimental: [false]
                include:
                  - php-versions: '8.5'
                    experimental: true

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    ini-values: memory_limit=1G

            -   name: Run batch script
                run: test\adjust_composer_for_php80.bat
                shell: cmd

            -   name: Install Composer dependencies
                run: composer update --no-progress --no-suggest --prefer-dist --optimize-autoloader

            -   name: Tests
                run: vendor/bin/phpunit --exclude-group linux
